### ISSUE TITLE
Database Connection Issue due to misleading "new" keyword

### ISSUE THREAD

**Issue by mohit1301** [swarup4/snowflake-orm#3]
connect: (connectionObj) => {
        return new Promise(function (resolve, reject) {
            **_`new`_** snowflakeConnection(connectionObj).then(data => {
                dbConnection = data;
                resolve('Successfully connected to Snowflake.');
            }, err => {
                reject("Unable to connect: " + err.message);
            });
        });
    },
    
    

In the above code of "`index.js file`", the "`new`" keyword before the "`snowflakeConnection`" is misleading, due to which we are not able to connect to the Snowflake DB. Kindly make the changes in the respective file.

**Comment by swarup4** [comment]
Thank you Mohit. I've fixed the issue. Now you can check. I hope it will work for you.
